export enum SurpriseScope {
  ANYWHERE = 'ANYWHERE',
  DOMESTIC = 'DOMESTIC',
  INTERNATIONAL = 'INTERNATIONAL',
}

export enum SurpriseActivityCategory {
  ACCOMMODATION = 'ACCOMMODATION',
  SIGHTSEEING = 'SIGHTSEEING',
  FOOD = 'FOOD',
  ACTIVITY = 'ACTIVITY',
  TRANSPORT = 'TRANSPORT',
  RELAXATION = 'RELAXATION',
  SHOPPING = 'SHOPPING',
  NIGHTLIFE = 'NIGHTLIFE',
}
